export type Product = {
  name: string;
  category: string;
  price: number;
  description: string;
  gumroadUrl: string;
  payhipUrl: string;
  tags: string[];
};

export const N8N_PACKS: Product[] = [
  { name: "Freelancer Automation Pack", category: "n8n", price: 39, description: "Client onboarding, invoicing, follow-ups, project tracking workflows for freelancers.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/hvlkg", payhipUrl: "https://payhip.com/b/ZKDRt", tags: ["freelance", "invoicing", "client management", "solopreneur"] },
  { name: "Agency Automation Pack", category: "n8n", price: 49, description: "Lead gen, client delivery, reporting, and team ops workflows for agencies.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/menhmu", payhipUrl: "https://payhip.com/b/uwX9J", tags: ["agency", "marketing", "lead generation", "client delivery"] },
  { name: "E-Commerce Automation Pack", category: "n8n", price: 49, description: "Order processing, inventory alerts, customer follow-ups, review requests.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/qvqrlk", payhipUrl: "https://payhip.com/b/KRYh3", tags: ["ecommerce", "shopify", "orders", "inventory", "retail"] },
  { name: "SaaS + Creator Automation Pack", category: "n8n", price: 49, description: "Trial onboarding, churn detection, creator analytics, sponsorship workflows.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/uetqpy", payhipUrl: "https://payhip.com/b/fKNth", tags: ["saas", "creator", "onboarding", "churn", "subscription"] },
  { name: "HR + Ops Automation Pack", category: "n8n", price: 49, description: "Hiring pipelines, onboarding checklists, leave tracking, policy distribution.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/uppinv", payhipUrl: "https://payhip.com/b/Sjd5s", tags: ["hr", "hiring", "onboarding", "operations", "people"] },
  { name: "Marketing Automation Pack", category: "n8n", price: 49, description: "Content scheduling, lead scoring, email campaigns, social media workflows.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/vcaye", payhipUrl: "https://payhip.com/b/rEfLt", tags: ["marketing", "email", "social media", "content", "leads"] },
  { name: "Finance + Accounting Automation Pack", category: "n8n", price: 49, description: "Invoice automation, expense tracking, reconciliation, financial reporting.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/ydtvi", payhipUrl: "https://payhip.com/b/YxIh9", tags: ["finance", "accounting", "invoicing", "bookkeeping", "expenses"] },
  { name: "Customer Support Automation Pack", category: "n8n", price: 49, description: "Ticket routing, auto-responses, escalation, CSAT tracking workflows.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/gzind", payhipUrl: "https://payhip.com/b/mS2iJ", tags: ["customer support", "helpdesk", "tickets", "service"] },
  { name: "Project Management Automation Pack", category: "n8n", price: 49, description: "Task creation, deadline alerts, status reporting, team standup workflows.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/jncser", payhipUrl: "https://payhip.com/b/hY0Oy", tags: ["project management", "tasks", "team", "deadlines"] },
  { name: "Sales + CRM Automation Pack", category: "n8n", price: 49, description: "Lead capture, pipeline updates, follow-up sequences, deal tracking.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/poomtb", payhipUrl: "https://payhip.com/b/x7QDE", tags: ["sales", "crm", "leads", "pipeline", "follow-up"] },
  { name: "Content Creator Automation Pack", category: "n8n", price: 49, description: "Script-to-publish pipelines, repurposing, scheduling, analytics workflows.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/jqcdt", payhipUrl: "https://payhip.com/b/lp8cF", tags: ["content", "youtube", "creator", "publishing", "social"] },
  { name: "Real Estate + Property Management Pack", category: "n8n", price: 49, description: "Lead routing, inspection scheduling, rent reminders, tenant comms.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/sivcn", payhipUrl: "https://payhip.com/b/UuFgZ", tags: ["real estate", "property management", "landlord", "tenants"] },
  { name: "Legal + Compliance Automation Pack", category: "n8n", price: 49, description: "Contract tracking, deadline alerts, compliance checklists, document workflows.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/jtasx", payhipUrl: "https://payhip.com/b/6qINi", tags: ["legal", "compliance", "contracts", "law firm"] },
  { name: "Healthcare + Practice Automation Pack", category: "n8n", price: 49, description: "Appointment reminders, patient comms, billing workflows, referral tracking.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/eblkej", payhipUrl: "https://payhip.com/b/MS3DO", tags: ["healthcare", "medical", "clinic", "appointments", "patients"] },
  { name: "Restaurant + Hospitality Automation Pack", category: "n8n", price: 49, description: "Reservation management, supplier orders, staff scheduling, review tracking.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/brlutr", payhipUrl: "https://payhip.com/b/vwnIQ", tags: ["restaurant", "hospitality", "food", "reservations", "staff"] },
  { name: "Bookkeeping Automation Pack", category: "n8n", price: 49, description: "Receipt capture, expense categorisation, GST tracking, report generation.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/wvtvhy", payhipUrl: "https://payhip.com/b/Vgq75", tags: ["bookkeeping", "accounting", "gst", "tax", "expenses"] },
  { name: "Recruitment + Hiring Automation Pack", category: "n8n", price: 49, description: "Job post distribution, applicant tracking, interview scheduling, offer workflows.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/isbfh", payhipUrl: "https://payhip.com/b/RklJE", tags: ["recruitment", "hiring", "hr", "applicants", "interviews"] },
  { name: "Gym + Fitness Studio Automation Pack", category: "n8n", price: 49, description: "Member check-ins, class reminders, renewal alerts, trainer assignment.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/isdet", payhipUrl: "https://payhip.com/b/6r7oV", tags: ["gym", "fitness", "studio", "members", "classes"] },
  { name: "Logistics + Shipping Automation Pack", category: "n8n", price: 49, description: "Shipment tracking, delay alerts, carrier updates, delivery confirmation flows.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/fmuyrn", payhipUrl: "https://payhip.com/b/fVPvt", tags: ["logistics", "shipping", "ecommerce", "fulfilment", "tracking"] },
  { name: "Photography + Creative Studio Automation Pack", category: "n8n", price: 49, description: "Booking workflows, gallery delivery, client follow-ups, contract signing.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/vqqtw", payhipUrl: "https://payhip.com/b/UnlhY", tags: ["photography", "creative", "studio", "bookings", "galleries"] },
  { name: "IT Service Desk Automation Pack", category: "n8n", price: 49, description: "Ticket triage, SLA tracking, escalation routing, knowledge base updates.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/juhqor", payhipUrl: "https://payhip.com/b/R7VC6", tags: ["it", "service desk", "helpdesk", "tickets", "sla"] },
  { name: "YouTube Creator Automation Pack", category: "n8n", price: 49, description: "Upload scheduling, comment triage, analytics tracking, sponsorship outreach.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/looti", payhipUrl: "https://payhip.com/b/DHmsB", tags: ["youtube", "creator", "video", "channel", "monetisation"] },
];

export const OBSIDIAN_VAULTS: Product[] = [
  { name: "Freelancer Business OS", category: "obsidian", price: 25, description: "Complete Obsidian vault for freelancer business management: clients, projects, invoices, goals.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/sfqzcz", payhipUrl: "https://payhip.com/b/L2Jvq", tags: ["freelance", "business", "clients", "projects"] },
  { name: "Project Manager OS", category: "obsidian", price: 25, description: "Obsidian vault for project managers: roadmaps, stakeholders, risks, retrospectives.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/hmwio", payhipUrl: "https://payhip.com/b/3f7tl", tags: ["project management", "roadmap", "team"] },
  { name: "Side Hustle OS", category: "obsidian", price: 25, description: "Track your side hustle: income, expenses, tasks, ideas and growth in Obsidian.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/aptjke", payhipUrl: "https://payhip.com/b/r2d1Z", tags: ["side hustle", "freelance", "income", "solopreneur"] },
  { name: "Personal Finance OS", category: "obsidian", price: 25, description: "Budget tracking, net worth, savings goals, and spending analysis in Obsidian.", gumroadUrl: "https://zarchitectstudio.gumroad.com/l/fpiha", payhipUrl: "https://payhip.com/b/ygiAm", tags: ["personal finance", "budget", "savings", "money"] },
];

export const ALL_PRODUCTS = [...N8N_PACKS, ...OBSIDIAN_VAULTS];
