export type WorkflowInput = {
  businessType: string;
  painPoints: string;
  currentTools: string;
  recommendations: Array<{ product: { name: string; tags: string[] }; expectedImpact: string }>;
};

type N8NNode = {
  id: string;
  name: string;
  type: string;
  typeVersion: number;
  position: [number, number];
  parameters: Record<string, unknown>;
  credentials?: Record<string, unknown>;
  notes?: string;
};

type N8NWorkflow = {
  name: string;
  nodes: N8NNode[];
  connections: Record<string, { main: Array<Array<{ node: string; type: string; index: number }>> }>;
  settings: Record<string, unknown>;
  meta: { instanceId: string };
};

function makeId(suffix: string) {
  return `appz-${suffix}-001`;
}

export function generateWorkflow(input: WorkflowInput): N8NWorkflow {
  const { businessType, painPoints, recommendations } = input;

  const tags = recommendations.flatMap(r => r.product.tags);
  const isFreelancer = tags.some(t => ["freelance", "invoicing", "solopreneur"].includes(t));
  const isBookkeeping = tags.some(t => ["bookkeeping", "gst", "tax", "accounting"].includes(t));
  const isMarketing = tags.some(t => ["marketing", "email", "leads"].includes(t));
  const isHR = tags.some(t => ["hr", "hiring", "onboarding"].includes(t));

  const nodes: N8NNode[] = [];
  const connections: N8NWorkflow["connections"] = {};

  // Always include: BAS quarterly reminder trigger
  nodes.push({
    id: makeId("trigger"),
    name: "AU Quarterly BAS Reminder",
    type: "n8n-nodes-base.scheduleTrigger",
    typeVersion: 1,
    position: [260, 300],
    parameters: {
      rule: {
        interval: [{ field: "cronExpression", expression: "0 9 25 1,4,7,10 *" }],
      },
    },
    notes: "Fires on the 25th of Jan, Apr, Jul, Oct -- 3 days before each BAS quarter closes (28th)",
  });

  // Super guarantee reminder (separate schedule)
  nodes.push({
    id: makeId("super"),
    name: "Super Guarantee Due Alert",
    type: "n8n-nodes-base.scheduleTrigger",
    typeVersion: 1,
    position: [260, 480],
    parameters: {
      rule: {
        interval: [{ field: "cronExpression", expression: "0 9 25 1,4,7,10 *" }],
      },
    },
    notes: "Super guarantee due quarterly: 28 Jan, 28 Apr, 28 Jul, 28 Oct (11.5% of gross wages)",
  });

  // Email notification node (AU-specific content)
  const basEmailContent = `Your AU Business Compliance Checklist:

BAS LODGEMENT (due 28 ${new Date().toLocaleString("en-AU", { month: "long" })}):
1. Log into Xero/MYOB and run GST report for the quarter
2. Verify all GST categories are correct
3. Reconcile bank account
4. Lodge BAS via ATO Business Portal or MyGovID
5. Pay any GST owing by due date

SUPER GUARANTEE (due 28 ${new Date().toLocaleString("en-AU", { month: "long" })}):
- Rate: 11.5% of ordinary time earnings
- Must be paid to employee super funds via SuperStream
- Late payment = Super Guarantee Charge (SGC) penalty applies

PAYROLL (STP):
- Ensure all pay events have been reported to ATO via STP
- Finalise by 14 July each year

This workflow was generated by AppZ AU Business Advisor (gemini-xprize.vercel.app)`;

  nodes.push({
    id: makeId("email"),
    name: "Send AU Compliance Email",
    type: "n8n-nodes-base.emailSend",
    typeVersion: 2,
    position: [500, 300],
    parameters: {
      fromEmail: "automation@yourbusiness.com.au",
      toEmail: "={{ $env.OWNER_EMAIL || 'owner@yourbusiness.com.au' }}",
      subject: "AU Business Compliance Checklist -- Quarter Closing",
      text: basEmailContent,
    },
  });

  connections[makeId("trigger")] = {
    main: [[{ node: makeId("email"), type: "main", index: 0 }]],
  };

  // Add business-specific nodes
  if (isFreelancer || painPoints.toLowerCase().includes("invoice")) {
    nodes.push({
      id: makeId("invoice"),
      name: "Chase Overdue Invoices",
      type: "n8n-nodes-base.scheduleTrigger",
      typeVersion: 1,
      position: [260, 640],
      parameters: {
        rule: { interval: [{ field: "cronExpression", expression: "0 9 * * 1" }] },
      },
      notes: "Every Monday 9am -- check for invoices overdue 7+ days and send chase email",
    });

    nodes.push({
      id: makeId("invoice-http"),
      name: "Get Overdue Invoices (Xero)",
      type: "n8n-nodes-base.httpRequest",
      typeVersion: 4,
      position: [500, 640],
      parameters: {
        method: "GET",
        url: "https://api.xero.com/api.xro/2.0/Invoices?Status=AUTHORISED&DueDateTo={{ $today.minus({days: 7}).format('YYYY-MM-DD') }}",
        authentication: "genericCredentialType",
        genericAuthType: "oAuth2Api",
        sendHeaders: true,
        headerParameters: {
          parameters: [{ name: "Accept", value: "application/json" }],
        },
      },
      notes: "Requires Xero OAuth2 credentials. Set up at: Settings > Credentials > New Credential > Xero OAuth2 API",
    });

    connections[makeId("invoice")] = {
      main: [[{ node: makeId("invoice-http"), type: "main", index: 0 }]],
    };
  }

  if (isBookkeeping || painPoints.toLowerCase().includes("bas") || painPoints.toLowerCase().includes("gst")) {
    nodes.push({
      id: makeId("gst"),
      name: "Monthly GST Reconciliation Check",
      type: "n8n-nodes-base.scheduleTrigger",
      typeVersion: 1,
      position: [260, 800],
      parameters: {
        rule: { interval: [{ field: "cronExpression", expression: "0 9 1 * *" }] },
      },
      notes: "First of each month -- pull GST summary from Xero and email for review",
    });
  }

  if (isMarketing || businessType.toLowerCase().includes("agency") || businessType.toLowerCase().includes("marketing")) {
    nodes.push({
      id: makeId("leads"),
      name: "New Lead Notification",
      type: "n8n-nodes-base.webhook",
      typeVersion: 1,
      position: [260, 960],
      parameters: {
        httpMethod: "POST",
        path: "new-lead",
        responseMode: "onReceived",
      },
      notes: "Webhook URL -- paste into your website contact form or Typeform to capture leads",
    });
  }

  if (isHR || businessType.toLowerCase().includes("hire") || painPoints.toLowerCase().includes("staff")) {
    nodes.push({
      id: makeId("stp"),
      name: "STP Payroll Reminder",
      type: "n8n-nodes-base.scheduleTrigger",
      typeVersion: 1,
      position: [260, 1120],
      parameters: {
        rule: { interval: [{ field: "cronExpression", expression: "0 8 * * 4" }] },
      },
      notes: "Thursday 8am -- reminder to process payroll (most AU SMBs pay weekly/fortnightly on Friday)",
    });
  }

  return {
    name: `AU Business Automation -- ${businessType} (AppZ)`,
    nodes,
    connections,
    settings: {
      executionOrder: "v1",
      saveManualExecutions: true,
      callerPolicy: "workflowsFromSameOwner",
    },
    meta: {
      instanceId: "appz-au-business-advisor-gemini-xprize",
    },
  };
}
